### ISSUE TITLE
add Table of contents in the PDF

### ISSUE THREAD

**Issue by VitalyAnkh** [shriram/plai-public#43]
### Contact Details

vr@vitalyr.com

### Which part are you commenting on?

Table of contents

### What's your suggestion?

The PDF should include a Table of Contents to enhance readability.

**Comment by shriram** [comment]
Yes, it would be nice. Unfortunately, the document is produced by Google Docs, and Google Docs does not seem to generate one. I'm at their mercy. Even the TOC that is on PDF page 2 onwards is generated at some pain.

A quick search showed at least one other person who has this problem, so it's likely not just a skill issue on my part:

https://support.google.com/docs/thread/206327014/how-to-make-a-table-of-contents-in-the-left-sidebar-of-a-pdf?hl=en

I am hoping that Google will fix this automatically, since they clearly have the necessary metadata, given that they are able to generate the in-document TOC.

I'm going to close this, not because I don't think it's important, but rather because, while I agree, it depends on Google Docs doing the right thing, and when they do, the problem will be fixed automatically: I likely won't have to do anything to enable it.
